mykey = "clarusway"
ami = "ami-0ebfd941bbafe70c6"
region = "us-east-1"
instance_type = "t3a.medium"
nexus_server_secgr = "petclinic-nexus-server-secgr"
nexus-server-tag = "Nexus Server of Petclinic"
